version: "3"
services:
  rabbitmq:
    container_name: rabbit
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_VHOST=test