version: "3"
services:
  api:
    container_name: api
    build: 
      dockerfile: Api/Dockerfile
      context: src/FinancialCalculator
    ports:
      - "5000:5000"
    restart: on-failure:5
    depends_on:
      - rabbitmq
  rabbitmq:
    container_name: rabbit
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_VHOST=test