version: "3"
services:
  api:
    container_name: api
    build: 
      dockerfile: Api/Dockerfile
      context: src/FinancialCalculator
    ports:
      - "5000:80"
    restart: on-failure:5
    depends_on:
      - rabbitmq
    
  credit:
    container_name: credit
    build: 
      dockerfile: Services/Credit/Dockerfile
      context: src/FinancialCalculator
    restart: on-failure:5
    depends_on:
      - rabbitmq
  rabbitmq:
    container_name: rabbit
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_VHOST=test
  ui:
    container_name: ui
    build:
      dockerfile: Dockerfile
      context: ui/financial-calculator
    ports:
      - "8080:80"